---
#
# Ansible managed
#

name: "TODO 2 Issue"

on:
  push:

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v3.0.2"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.9"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
